<template>
    <div> <ProjectDetailHeader :project="project" /></div>
<div class="paragraph">
    <h3>Overview</h3> 
        <strong>The Verdant Revival</strong> is a survival game using Unity Engine. It is an adventure where the player steps into a world that’s gray and full of pollution. 
        Here, player's mission is to clean up the mess and turn the island from gray to green. 
        Do this by gathering trash, recycling it into handy items, and reviving tons of trees and plants.
        <br>
        <br>
        It was my individual courwork for CPT306-2223-S2-Principles of Computer Games Design.
        <br>
        <br>
        Here is the demo video of the prototype:
        </div>

    <div class="paragraph center">
    <video controls style="width:100%; max-width:1920px; height:auto;" poster="https://images.tsingloo.com/TheVerdantRevival_Demo.jpg">>
        <source src="https://game.tsingloo.com/Videos/TheVerdantRevival_Demo.mp4" type="video/mp4">
        Your browser does not support the video tag.
    </video>
</div>

<div>
    <div class="notice">
    Download the Windows Build from <a href="https://game.tsingloo.com/backup/TheVerdantRevival.zip" target="_blank">here<i class="fa fa-file-zip-o"></i></a>, 
    Game Design Report is available <a href="https://game.tsingloo.com/backup/TheVerdantRevival_GameDesignReport.pdf" target="_blank">here<i class="fa fa-file-pdf-o"></i></a>
    </div>
</div>

    <div class="paragraph">
    <h3>Main Features</h3> 
        <ul>
        <li>Environmental estoration mechanic</li>
        <li>Day-Night cycle</li>
        <li>Energy mechanic</li>
        <li>Perlin Noise-based map generator with seed</li>
        <li>Performance optimization by <a href="https://docs.unity3d.com/Manual/JobSystem.html">Job System</a></li>
        </ul>
    </div>

    <div class="paragraph">
    <h3>Technical Insights</h3>
    <strong>The Verdant Revival</strong>'s UI Manager comes from my <a href="https://github.com/TsingLoo/TinyUFramework/tree/main"><i class="fa fa-github fa-lg fa-fw"></i>TinyUFramework</a> and works well 
    with <a href="https://feel.moremountains.com/" target="_blank">FEEL</a> to load the scene and enhance interaction feedback. 
    It automatically registers the UI Panel prefabs in the asset folder and maintains their states to support the switch between different panels.
    <br>
    <br>
    The project uses the Burst Compiler to parallel the movements of blue cubes to simulate sea waves, getting a 2x performance boost rather than assigning a Monobehaviour to each cube to update its position in the main thread.
    The terrain is generated by Perlin Noise, and the nested ground cubes are removed to improve the performance further. The trees, rocks and toxics are distributed according to certain conditions (e.g., the trees are only generated on a 4x4 plain ground, and the corresponding ground will not instantiate toxics).
    <br>
    <br>
    Inspired by <a href="https://zelda.nintendo.com/tears-of-the-kingdom/">Zelda</a>, the game has a day-night cycle and the player's energy is demonstrated as a green ring.
    The energy will be recovered when the player is idle for a certain time and reduced when the player dashes. 
    The various feedbacks, screen effects and sounds are added to improve the overall feeling and experience.
    </div>
</template>

<script setup lang="ts">
// Using <script setup> makes this much more concise
import { type PropType } from 'vue'; // 'type' import for PropType
import type ProjectData from '@/data/ProjectData'; // Adjust path as needed
import ProjectDetailHeader from '@/components/ProjectDetailHeader.vue'; // Import the new header

// Define props using defineProps compiler macro
const props = defineProps({
  project: {
    type: Object as PropType<ProjectData>,
    required: false // Or true, if ProjectDetailView always supplies it.
                  // If true, you might not need the v-if="project" checks in the template as much,
                  // but it's safer to keep them if the project prop could ever be null/undefined initially.
  }
});
</script>